version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./backend/data:/app/backend/data
    environment:
      - DOCKER_ENV=true
    restart: unless-stopped
